//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRB_BDI
    {
        public System.DateTime Publish_Date { get; set; }
        public decimal BDI { get; set; }
        public decimal CRB { get; set; }
        public decimal Oil { get; set; }
    }
}
