//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanceEntities : DbContext
    {
        public FinanceEntities()
            : base("name=FinanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exchange> Exchanges { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Libor> Libors { get; set; }
        public virtual DbSet<MonetaryAggregate> MonetaryAggregates { get; set; }
        public virtual DbSet<Taifex> Taifexes { get; set; }
        public virtual DbSet<Macroeconomic> Macroeconomics { get; set; }
        public virtual DbSet<BullAndBear> BullAndBears { get; set; }
        public virtual DbSet<CYQ> CYQs { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<CRB_BDI> CRB_BDI { get; set; }
    }
}
