//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guestbooks
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Reply { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public string MembersAccount { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
