//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libor
    {
        public System.DateTime QuotedDate { get; set; }
        public decimal C0N { get; set; }
        public decimal C1W { get; set; }
        public decimal C1M { get; set; }
        public decimal C3M { get; set; }
        public decimal C6M { get; set; }
        public decimal C12M { get; set; }
    }
}
