//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Macroeconomic
    {
        public System.DateTime Publish_Date { get; set; }
        public decimal CPI { get; set; }
        public decimal CPI_GrowthRate { get; set; }
        public decimal CCPI { get; set; }
        public decimal CCPI_GrowthRate { get; set; }
        public decimal PPI_GrowthRate { get; set; }
        public decimal Unemployment_Rate { get; set; }
        public int NFP { get; set; }
        public decimal Weekly_Work_Hours { get; set; }
        public decimal Hourly_WageRate { get; set; }
        public decimal Export_IncreasedRate { get; set; }
        public decimal Export_PriceRate { get; set; }
        public decimal Import_IncreasedRate { get; set; }
        public decimal Import_PriceRate { get; set; }
        public decimal Housing_Starts { get; set; }
        public decimal Housing_Starts_GrowthRate { get; set; }
        public decimal Retail_Sales_Rate { get; set; }
        public decimal Retail_Sales_Rate_NoCar { get; set; }
        public decimal Personal_Expenditure_Rate { get; set; }
        public decimal Individual_Income_Rate { get; set; }
        public decimal ICS { get; set; }
        public decimal Capacity_Utilization { get; set; }
        public decimal Durable_Orders { get; set; }
        public decimal Factory_Orders { get; set; }
        public decimal Factory_Stock { get; set; }
        public decimal Factory_Shipments { get; set; }
        public decimal Manufacturing_PMI { get; set; }
        public decimal PMI { get; set; }
    }
}
