//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Id { get; set; }
        public string stockName { get; set; }
        public int Volume { get; set; }
        public System.DateTime Price_Date { get; set; }
        public decimal Price_Open { get; set; }
        public decimal Price_High { get; set; }
        public decimal Price_Low { get; set; }
        public decimal Price_Close { get; set; }
    }
}
