//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taifex
    {
        public System.DateTime QuotedDate { get; set; }
        public decimal Future_Foreign_Buy { get; set; }
        public decimal Future_Foreign_Sell { get; set; }
        public decimal Future_Foreign_Net { get; set; }
        public decimal Future_Dealer_Buy { get; set; }
        public decimal Future_Dealer_Sell { get; set; }
        public decimal Future_Dealer_Net { get; set; }
        public decimal Future_Top5_Buy { get; set; }
        public decimal Future_Top5_Buy_Percent { get; set; }
        public decimal Future_Top5_Sell { get; set; }
        public decimal Future_Top5_Sell_Percent { get; set; }
        public decimal Future_Top10_Buy { get; set; }
        public decimal Future_Top10_Buy_Percent { get; set; }
        public decimal Future_Top10_Sell { get; set; }
        public decimal Future_Top10_Sell_Percent { get; set; }
        public decimal Option_Foreign_Buy { get; set; }
        public decimal Option_Foreign_Sell { get; set; }
        public decimal Option_Foreign_Net { get; set; }
        public decimal Option_Dealer_Buy { get; set; }
        public decimal Option_Dealer_Sell { get; set; }
        public decimal Option_Dealer_Net { get; set; }
        public decimal Option_Top5_Long_Buy { get; set; }
        public decimal Option_Top5_Long_Buy_Percent { get; set; }
        public decimal Option_Top5_Long_Sell { get; set; }
        public decimal Option_Top5_Long_Sell_Percent { get; set; }
        public decimal Option_Top10_Long_Buy { get; set; }
        public decimal Option_Top10_Long_Buy_Percent { get; set; }
        public decimal Option_Top10_Long_Sell { get; set; }
        public decimal Option_Top10_Long_Sell_Percent { get; set; }
        public decimal Option_Top5_Short_Buy { get; set; }
        public decimal Option_Top5_Short_Buy_Percent { get; set; }
        public decimal Option_Top5_Short_Sell { get; set; }
        public decimal Option_Top5_Short_Sell_Percent { get; set; }
        public decimal Option_Top10_Short_Buy { get; set; }
        public decimal Option_Top10_Short_Buy_Percent { get; set; }
        public decimal Option_Top10_Short_Sell { get; set; }
        public decimal Option_Top10_Short_Sell_Percent { get; set; }
    }
}
