//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int Stock_Number { get; set; }
        public System.DateTime Publish_Date { get; set; }
        public decimal VoucherRatio { get; set; }
        public decimal DayTradingRatio { get; set; }
        public decimal FinancingValue { get; set; }
        public decimal MarginValue { get; set; }
    }
}
